In [13]:
import numpy as np 
a=np.array([1,2,3,45,78,91])
print(a)
list1=a.tolist()
print(list1)

[ 1  2  3 45 78 91]
[1, 2, 3, 45, 78, 91]


In [ ]:
import numpy as np
arr=np.array([[23,56,48],[91,58,47]])
s=np.trace(arr)
print(s)

81


In [20]:
import numpy as np 
a=np.array([[56,88,75,33],[39,48,63,95]]) 
x=50
b=a[a>x]
print(b)





[56 88 75 63 95]


In [22]:
import numpy as np 
a=np.array([[12,3,55,64,87,36]])
b=np.array([[37,99,41,25,68,56]])
c=a+b
print(c)

[[ 49 102  96  89 155  92]]


In [29]:
import numpy as np
a=np.array([[19,65,28,24]])
print(a)
b=a-a.mean(axis=1,keepdims=True)
print(b)


[[19 65 28 24]]
[[-15.  31.  -6. -10.]]
